[build]
  command = "pnpm run generate"
  publish = "dist"

[[redirects]]
  from = "/mastodon"
  to = "https://hachyderm.io/@praz"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/prazdevs"

[[redirects]]
  from = "/github"
  to = "https://github.com/prazdevs/"
